# Generated by Django 3.0.3 on 2020-02-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='question',
            field=models.ManyToManyField(related_name='questions', to='polls.Question'),
        ),
    ]
