# Generated by Django 3.0.3 on 2020-02-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20200215_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('username', models.DateField(auto_now_add=True, verbose_name='用户注册日期')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('summary', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签名')),
                ('article', models.ManyToManyField(to='booktest.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Concact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, verbose_name='用户手机号')),
                ('email', models.EmailField(default='1751522491@qq.com', max_length=254, verbose_name='用户邮箱')),
                ('concact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='con', to='booktest.Account')),
            ],
        ),
    ]
