# Generated by Django 3.0.3 on 2020-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_account_article_concact_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='regist_date',
            field=models.DateField(default='2020-2-15', verbose_name='用户注册日期'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='booktest.Article'),
        ),
    ]
