# Generated by Django 3.0.3 on 2020-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='recommend', verbose_name='图片')),
                ('desc1', models.CharField(blank=True, max_length=20, null=True, verbose_name='图片描述')),
                ('desc2', models.CharField(blank=True, max_length=20, null=True, verbose_name='图片描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
