# Generated by Django 3.0.3 on 2020-02-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0003_auto_20200225_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='标题', max_length=5, verbose_name='活动标题'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=12, verbose_name='用户名'),
        ),
    ]
