# Generated by Django 3.0.4 on 2020-03-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juncinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.BooleanField(choices=[('True', '男'), ('False', '女')], default='True', verbose_name='性别'),
        ),
    ]
