# Generated by Django 3.0.4 on 2020-03-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juncinet', '0002_auto_20200329_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别'),
        ),
    ]
