# Generated by Django 3.0.3 on 2020-02-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='goodimg', verbose_name='商品展示图')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='shop.Good', verbose_name='商品')),
            ],
        ),
    ]
